### ISSUE TITLE
Differences between the concurrent NQTables dataset?

### ISSUE THREAD

**Issue by Jun-jie-Huang** [google-research/tapas#131]
Hi, 
  Thanks for your contributions to provide an easy-to-use toolkit for table representations. I'm studying the table retrieval problem recently. I notice a concurrent dataset [NQTables](https://arxiv.org/pdf/2101.10573.pdf) which is accepted by EACL 2021. Also it's mentioned in your NAACL 2021 paper. Since I have to use one of your datasets, so I'm curious  about the differences. Simply it seems the data statistics are different. Can you tell any other differences between your work and the EACL one? 

Thanks,

**Comment by eisenjulian** [comment]
As far as I understand, the biggest difference is that we made our dataset compatible with open domain Question Answering (that is, without a fixed, known in-advance reference table) and in order to do that we had to align everything to a fixed Wikipedia revision, since the NQ dataset has a different Wikipedia revision for every question, which yields conflicting versions of the different tables. In the same vein, our work focuses more on the retrieval part in order to build a realistic end-to-end system, whereas Zayats et al, focuses more on the case where a reference table is available.

**Comment by Jun-jie-Huang** [comment]
@eisenjulian Thanks for your rapid reply and the explanations! Now I see the major diference. Thanks!
