### ISSUE TITLE
missing annotated_text_pb2

### ISSUE THREAD

**Issue by g1644222** [google-research/tapas#142]
Thank you for your interesting research.

I am working along with Installation now.
I am getting an ImportError in the tox section.
<img width="788" alt="スクリーンショット" src="https://user-images.githubusercontent.com/48608464/138047876-8cdcb4db-2ede-44d1-873b-f5fc86a0fd09.png">

`from protos import annotated_text_pb2`
ImportError: cannot import name 'annotated_text_pb2'

**Comment by eisenjulian** [comment]
Hello, the corresponding file annotated_text.proto is present in the tapas/proto folder, so this leads me to believe that the proto file was not compiled successfully, can you check for earlier errors in your run, perhaps the protoc compiler wasn't found?

Otherwise if you can provide a colab to reproduce the error it would help a lot,

Cheers!

**Comment by g1644222** [comment]
Thank you for the quick response.

Before this error, pip install -e . The following error occurred in

<img width="1315" alt="エラーログ2" src="https://user-images.githubusercontent.com/48608464/138061757-a7018aa7-49a1-441a-8f52-969c24d06e83.png">

This error could be avoided by removing annotated_text_pb2.
Was that a bad idea?
