### ISSUE TITLE
Question about prev_label_ids creation

### ISSUE THREAD

**Issue by NielsRogge** [google-research/tapas#86]
Hi,

concerning the creation of the `prev_label_ids` token type ids: I see in the [code](https://github.com/google-research/tapas/blob/d8638f0909b3de32a85fe7491769d47d645d8e22/tapas/utils/tf_example_utils.py#L1154) that the index of a table-question pair in a batch is used to set them. If it's the first example in the batch, set them to zeros, if the index is > 0, then set them to the calculated `label_ids` of the previous table-question pair of the batch.

But: is it possible that this is only an approximation? Because questions do not have an equal length, then the previous label ids are not simply equal to the label ids of the previous example? Or am I missing something here? Maybe I can make it more clear using an example:

Suppose that we have the following 2 examples in a batch:

| tokenized example 1                            | [CLS] | what | is  | his | name | [SEP]    | his | name | is   | Niels | and   | he  | is | 24 | years | old   | [PAD] |
|------------------------------------------------|-----|------|-----|-----|------|--------|-----|------|------|-------|-------|-----|----|----|-------|-------|-----|
| label_ids                                      | 0   | 0    | 0   | 0   | 0    | 0      | 0   | 0    | 0    | 1     | 0     | 0   | 0  | 0  | 0     | 0     | 0   |
| tokenized_example 2                            | [CLS] | how  | old | is  | he   | really | [SEP] | his  | name | is    | Niels | and | he | is | 24    | years | old |
| prev_label_ids of example 2 (set to label_ids of example 1) | 0   | 0    | 0   | 0   | 0    | 0      | 0   | 0    | 0    | 1     | 0     | 0   | 0  | 0  | 0     | 0     | 0   |

Then the prev_label_ids of example 2 (which are set to the label ids of the first example), do not align with the tokens.
 
And second question: for datasets such as WTQ, WikiSQL, should they always be set to zeros, as they're not conversational?

**Comment by thomasmueller-google** [comment]
The code you point to is the TF conversion that happens before batching.
At this point we will have a sequence of questions that all refer to the same table.
The code should map a cell coordinate (row and column index) to the right indices in the sequence.
You are right in that this position might change because it depends on the length of the question.

The code that maps from cell to index is [here](https://github.com/google-research/tapas/blob/d8638f0909b3de32a85fe7491769d47d645d8e22/tapas/utils/tf_example_utils.py#L196):

```python
def _get_all_answer_ids_from_coordinates(
    column_ids,
    row_ids,
    answers_list,
):
  """Maps lists of answer coordinates to token indexes."""
  answer_ids = [0] * len(column_ids)
  found_answers = set()
  all_answers = set()
  for answers in answers_list:
    for column_index, row_index in answers:
      all_answers.add((column_index, row_index))
      for index in _get_cell_token_indexes(column_ids, row_ids, column_index,
                                           row_index):
        found_answers.add((column_index, row_index))
        answer_ids[index] = 1

  missing_count = len(all_answers) - len(found_answers)
  return answer_ids, missing_count
```

Does that help?

**Comment by thomasmueller-google** [comment]
We also have a piece of code that does this based on TF examples.

This is required during prediction when we want realistic prediction for a sequence we need to do this on the fly (because the prev label ids depend on the previous prediction):

The code is [here](https://github.com/google-research/tapas/blob/d8638f0909b3de32a85fe7491769d47d645d8e22/tapas/experiments/prediction_utils.py#L92)

**Comment by NielsRogge** [comment]
> At this point we will have a sequence of questions that all refer to the same table.

Yes I understand that the questions of a batch all refer to the same table. And I am using the same function that you quote in my implementation. 

So the answer to my question is... yes? It is possible that the `prev_label_ids` are not set correctly, due to the fact that questions have different lengths? Wouldn't performance increase if you set the `prev_label_ids` based on `len(question_tokens)` of both the current and previous question?  This can easily be achieved in the `convert` function, by keeping a dictionary that maps an index of a question in the batch to its number of question tokens (including [CLS] and [SEP]). 

Suppose this dictionary is called `index2len_question_tokens`. Each time you tokenize a question, you can store its length into this dictionary, as follows:

```
text_tokens = self._tokenize_extended_question(question, table) 
index2len_question_tokens[index] = len(text_tokens) 
```

Then you can replace

`prev_answer_ids = get_answer_ids(interaction.questions[index - 1],)` (from [this line](https://github.com/google-research/tapas/blob/d8638f0909b3de32a85fe7491769d47d645d8e22/tapas/utils/tf_example_utils.py#L1155))

by 

`prev_answer_ids = [0]*index2len_question_tokens[index] + get_answer_ids(interaction.questions[index - 1],)[index2len_question_tokens[index - 1]:]`

**Comment by muelletm** [comment]
I think the current code should work correctly.

The important part is that this inline function:

```python
    def get_answer_ids(question):
      if self._update_answer_coordinates:
        return _find_answer_ids_from_answer_texts(
            column_ids,
            row_ids,
            tokenized_table,
            answer_texts=[
                self._tokenizer.tokenize(at)
                for at in question.answer.answer_texts
            ],
        )
      return _get_answer_ids(column_ids, row_ids, question)
```

Captures `column_ids`, `row_ids`.

So we will use the column and rowl coordinates from the previous question, but the positions in the serialized sequence will be computed for the current query.

Does that make sense?

Can you otherwise give a test case where the ids are currently incorrect?

**Comment by NielsRogge** [comment]
Oh ok, I understand now! Thanks for the clarification.
